services:
  semistatic-test:
    image: semistatic-nginx
    environment:
      - REPO=https://github.com/josephreed2600/semistatic-nginx.git # git
      - FREQUENCY=* * * * * # cron format
      - DIR=doc # optional
    ports:
      - 80:80
